spring:
  datasource:
    url: jdbc:h2:mem:testdb
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    properties:
      hibernate:
        show_sql: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/